enum {
  // RF24 - Communication
  NAME_RECEIVED = 5,
  ADDDRESS_CHANGE_CONFIRMED = 15,
  CHANNEL_CHANGE_REQUEST = 20,
  CHANNEL_CHANGE_CONFIRMED = 25,
  CONTROLL_PACKET = 55,

  // Dev Tools
  ENABLE_LOGGER = 81,
  DISABLE_LOGGER = 80
} commandsIn;

enum {
  REQUEST_NAME = 1,
  REQUEST_ADDRESSCHANGE = 10,
  REQUEST_CHANNEL_CHANGE = 20,
  REQUEST_CONTROL_PACKET = 50
} commandsOut;
