#ifndef CONFIGS_HPP
#define CONFIGS_HPP

//#include "./modules/bt_connection/bt_connection.h"
#include "./modules/arduino_ota/arduino_ota_config.h"
#include "./modules/control_priority/control_priority_config.h"
#include "./modules/current_monitor/current_monitor_config.h"
#include "./modules/dead_man_switch/dead_man_switch_config.h"
#include "./modules/direct_power_modulation/direct_power_modulation.h"
#include "./modules/exponential_power_modulation/exponential_power_modulation_config.h"
#include "./modules/force_control/force_control_config.h"
#include "./modules/joystick_control/joystick_control_config.h"
#include "./modules/neopixels/neopixels_config.h"
#include "./modules/ntp_timeservice/ntp_timeservice_config.h"
#include "./modules/power_limit/power_limit_config.h"
#include "./modules/pwm_controller/pwm_controller_config.h"
#include "./modules/pwm_steering/pwm_steering_config.h"
#include "./modules/serial_control/serial_control_config.h"
#include "./modules/spiffs_drivelog/spiffs_drivelog_config.h"
#include "./modules/temperature_monitor/temperature_monitor_config.h"
#include "./modules/vesc_controller/vesc_controller_config.h"
#include "./modules/voltage_monitor/voltage_monitor_config.h"
#include "./modules/serial_control/serial_control_config.h"
#include "./modules/web_update/web_update_config.h"
#include "./modules/websocket_control/websocket_control_config.h"
#include "./modules/wifi_connection/wifi_connection_config.h"
#include "./modules/wifi_simple_control/wifi_simple_control_config.h"
#include "./modules/websocket_connection/websocket_connection_config.h"
#include "./modules/websocket_drivelog/websocket_drivelog_config.h"

#endif
